# Generated by Django 4.0.6 on 2022-12-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lang',
        ),
    ]
